"""empty message

Revision ID: ea07af79c409
Revises: 
Create Date: 2019-10-12 20:52:59.812000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea07af79c409'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('creater', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_suite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('creater', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=360), nullable=True),
    sa.Column('prescripts', sa.Text(), nullable=True),
    sa.Column('variables', sa.String(length=120), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Date(), nullable=True),
    sa.Column('end_time', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('creater', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=360), nullable=True),
    sa.Column('method', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=360), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.Column('auth', sa.Text(), nullable=True),
    sa.Column('allow_redirects', sa.Boolean(), nullable=True),
    sa.Column('proxies', sa.Text(), nullable=True),
    sa.Column('hooks', sa.Text(), nullable=True),
    sa.Column('stream', sa.Boolean(), nullable=True),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('cert', sa.Text(), nullable=True),
    sa.Column('json_str', sa.Text(), nullable=True),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('prescripts', sa.Text(), nullable=True),
    sa.Column('postscripts', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=True),
    sa.Column('content_size', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=120), nullable=True),
    sa.Column('end_time', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('test_case')
    op.drop_table('test_suite')
    op.drop_table('project')
    # ### end Alembic commands ###
